### ISSUE TITLE
Implementing a standard key manager API

### ISSUE THREAD

**Issue by joaquim-verges** [Consensys/web3signer#439]
I'm looking to help out on [this proposal](https://hackmd.io/@dapplion/web3signer#) by @dapplion.

Working branch: https://github.com/joaquim-verges/web3signer/tree/keymanager

The branch will be broken down into individual PRs for each of the main tasks below.

## Tasks breakdown

* [x] Extract existing signing API yaml definitions into their own files - #447 
* [x] Add new key manager API yaml definition - #455 
* [x] Add command line flag to enable API - #448 
* [x] Conditionally register routes + handlers in the Eth2Runner
* [x] Implement List handler + tests - #456
  * [x] Json model parsing
  * [x] Return the pubkeys from the artifact signer provider
  * [x] (bonus) add plumbing required to pass derivation_data in the response
* [x] Implement Import handler + tests - #462 
   * [x] Json model parsing
   * [x] Save keystores + passwords into a yaml config file with the expected format 
   * [x] That new yaml config file should be read and loaded in Eth2Runner#createArtifactSignerProvider as long as its saved in yaml format in the same keystore path passed through CLI 
   * [x] Invoke reload, which should just be a call to artifactSignerProvider.load() 
   * [x] Return expected response, handle errors
   * [x] Write unit tests
* [x] Implement Delete handler + tests - #489
    * [x] Json model parsing
    * [x] Find and delete the yaml files corresponding to the pubkeys coming from the request
    * [x] export slashing data for removed/non_active keys
    * [x] Return expected response, handle errors
    * [ ] Write unit tests
* [ ] Implement Authentication
    * [ ] Add Vertx JWT library dependency
    * [ ] Generate JWT token if doesn't exist or read from file and load in memory
    * [ ] Persist JWT token if doesn't exist on first generation
    * [ ] Add security handler to the OpenAPI router to verify the correct auth token is passed and fail otherwise

## Context

The high level goal of this work is to increase client diversity by making it easy for individual stakers to spin up a minority client. 

Working backwards from that high level goal, a possible solution would be to: 

- Enable the management of minority clients via a platform like [DAppNode](https://dappnode.io/). Right now Prysm is the only client supported.
- To do this, the other clients (Teku, Lodestar, Lighthouse, Nimbus) would ideally have a mini frontend for their client that can be accessed via the DappNode dashboard. At a minimum, the frontend needs to allow the user to manage keystores.
- Instead of each client building their own, that mini frontend could be standardized and built once for all clients, as long as they all talk to the same standardized API.

@dapplion has a [proposal for such standard API](https://github.com/ethereum/beacon-APIs/pull/151)

From there, a solution could be to implement that standard API in web3signer, and have the minority clients use web3signer as their remote signer following the [EIP-3030 standard](https://eips.ethereum.org/EIPS/eip-3030).

Any client doing this could get a simple, standard frontend "for free" to manage keys, and therefore would unlock the possibility to list them in a platform like [DAppNode](https://dappnode.io/), greatly simplifying the workflow for individual stakers.

## Open questions

Before I attempt an implementation of this API, I have some questions I'm hoping to get some answers to.

1. Is web3signer the right place to implement such API for key management?
2. web3signer already has an [API for remote signing](https://github.com/ConsenSys/web3signer/blob/942fece245c0874c2a59c4214126368bc8462b1e/core/src/main/resources/openapi/web3signer-eth2.yaml) - would it make sense to expand this API to support key management? Or is it cleaner to separate those, despite the fact that some of the functionality overlaps (both APIs have an endpoint to list public keys for example)
3. Is there any other concerns implementing this API as an opt-in with a command line flag?

Let me know if I'm thinking about this the right way, and please correct any of my assumptions!

**Comment by jframe** [comment]
hi @joaquim-verges,

Thank you for your proposal. It would be great to have these improvements to web3signer.

1. Think it does make sense for web3signer to have a key management API as web3signer is responsible for signing when used as the remote signer. The client will still need to be made aware that the keys have changed. Perhaps they will call the list keys endpoint?
2. It would be better to have a seperate API as in under a different namespace so it is clear this is a different API. There is a little bit of overlap with the list public keys endpoint but that is the only one.
3. An opt-in feature flag is good idea

Let us know if you have any more questions either here or on our discord channel.

**Comment by dapplion** [comment]
> hi @joaquim-verges,
> 
> Thank you for your proposal. It would be great to have these improvements to web3signer.
> 
>     1. Think it does make sense for web3signer to have a key management API as web3signer is responsible for signing when used as the remote signer. The client will still need to be made aware that the keys have changed. Perhaps they will call the list keys endpoint?
> 
>     2. It would be better to have a seperate API as in under a different namespace so it is clear this is a different API. There is a little bit of overlap with the list public keys endpoint but that is the only one.
> 
>     3. An opt-in feature flag is good idea
> 
> 
> Let us know if you have any more questions either here or on our discord channel.

Thanks for your input! Could you drop an invite to the Discord channel?

I agree this API routes should be served on a different namespace since the permissions will likely be very different

**Comment by joaquim-verges** [comment]
Thank you @jframe ! Started working on this and have follow up question on 2.

Right now there is an assumption that each runner has a single Open API spec resource (yaml file). I see three options here:

a. Put the new API definitions in the existing `web3signer-eth2.yaml`. I don't feel like this is right, the existing spec is already big, some types might overlap too which would make it messy.

b. Have a separate yaml spec for the new API. Correct me if I'm wrong, but this would requiring creating a separate `OpenAPI3RouterFactory` in `Eth2Runner`, which also doesn't feel right to me given the current Runner hierarchy structure. But maybe I'm missing something, or there's a way to cleanly do this multi spec approach with OpenAPI?

c. Another option could be to register additional routes in code on the existing `OpenAPI3RouterFactory`, only if the opt-in feature flag is passed in. SImilar to how it's done for the swagger endpoints [here](https://github.com/ConsenSys/web3signer/blob/942fece245c0874c2a59c4214126368bc8462b1e/core/src/main/java/tech/pegasys/web3signer/core/Runner.java#L232). This approach is a bit more dynamic and easy to add only in the `Eth2Runner`, but I we loose the nice yaml definitions. Again might be missing some functionality of OpenAPI I'm not aware of here.

Let me know what you think about these approaches, or if you can think of a better one?

**Comment by jframe** [comment]
hi @joaquim-verges,

So for option b, looks like the vertx openapi module we are using doesn't support multiple openapi specs for a single `OpenAPI3RouterFactory`. Not sure what will happen if multiple `OpenAPI3RouterFactory` are used on the same vertx router. But like you said this doesn't fit the existing design pattern we have either. So I don't think this is the preferred option.

I think option a will probably be the way to go with separating out the yaml files. It fits the existing pattern with each Runner having their own set of endpoints provided by a single openapi spec so will be easier to get started with. If you are able to seperate the key manager api to a seperate openapi spec file using $ref or another approach that would still keep the open api files relatively clean.

**Comment by joaquim-verges** [comment]
Thanks @jframe - that's where I was leaning towards as well. Will re-organize the yaml file a bit to keep it clean.

**Comment by joaquim-verges** [comment]
@jframe @dapplion here's another question/concern:

Currently:

- Right now an `Eth2Runner` is created and started when executing web3signer from the command line
- The available signing keys are loaded from a keystore file defined by `--key-store-path` when the runner is ran
- Those keys are final for the duration of the runner, loading new ones requires re-running the command

With the new API allowing to import keys, how do you envision the user flow? Can I import keys while my web3signer is running and dynamically add a new signing key or should it require a restart?

The latter would be simpler of course, we could just save the imported keystores into their own files and let the user know they need to restart their signer for the new keys to take effect? (same for delete keys i guess?)

@dapplion maybe you have a better idea of what the user flow should look like in this case?

**Comment by jframe** [comment]
@joaquim-verges

It is possible to load new keys without restarting web3signer by using the reload endpoint.

From a user flow perspective I think the ideal would be that as soon as the key was imported it would be available to use i.e. sign and available on the list keys endpoint. @dapplion Is this the intent of the import success case that once it is decrypted and in the key manager storage it is available to sign with?

**Comment by ajsutton** [comment]
Yep, the imported keys should be live straight away (which is how we're implementing it in Teku).  And for the delete case it's critically important that the keys are removed and can no longer sign before returning from the call. And that returned slashing protection data should be completely up to date. I wrote up a plan for handling this in memory in Teku at https://github.com/ConsenSys/teku/issues/4559 which may be useful - we'd also have to delete the files on disk to prevent them loading again on the next restart (I think we'd do that before deleting from memory to ensure we can).

**Comment by dapplion** [comment]
> With the new API allowing to import keys, how do you envision the user flow? Can I import keys while my web3signer is running and dynamically add a new signing key or should it require a restart?

> The latter would be simpler of course, we could just save the imported keystores into their own files and let the user know they need to restart their signer for the new keys to take effect? (same for delete keys i guess?)

@joaquim-verges Yes keys must be importable and deletable while the application is running.

**Comment by joaquim-verges** [comment]
@dapplion got it. One more question: should the keys imported via the API be persisted? Like if I restart web3signer, should it launch again with the previously imported keys?

Asking to know if it's enough to keep the keys imported via API in memory or if they need to be persisted on disk somewhere. I assume we want to persist the keys on disk, but want to make sure that's ok from a security standpoint?

**Comment by dapplion** [comment]
> should the keys imported via the API be persisted? Like if I restart web3signer, should it launch again with the previously imported keys?

Yes, imported keys must be persisted in disk. If that's not clear in the API spec please feel free to drop a comment there.

**Comment by joaquim-verges** [comment]
Ok, here's in my mind the list of tasks needed to make this happen:

- Extract existing signing API yaml definitions into their own files
- Add new key manager API yaml definition
- Implement List handler + tests
  - Json model parsing
  - Return the pubkeys from the artifact signer provider
  - (bonus) add plumbing required to pass derivation_data in the response
- Implement Import handler + tests
  - Json model parsing
  - Save keystores + passwords into a yaml config file with the expected format (@jframe can't find a Bls example of such yaml config file in the repo, can you help me get one for reference?)
  - That new yaml config file should be read and loaded in `Eth2Runner#createArtifactSignerProvider` as long as its saved in yaml format in the same keystore path passed through CLI (so no changes requried there I believe)
  - Invoke reload, which should just be a call to `artifactSignerProvider.load()` (just needs to be exposed, probably via a function in the base `Runner` class)
  - Return expected response, handle errors
  - Write unit tests
- Implement Delete handler + tests
  - Json model parsing
  - Find and delete the yaml files corresponding to the pubkeys coming from the request
  - Invoke reload - I think that should be enough? Though I see reload doesn't actually clear the existing keys, that might be an issue. @jframe any suggestions here? Otherwise we'd have to add the plumbing to dynamically remove keys from memory as @ajsutton mentioned.
  - Return expected response, handle errors
  - Write unit tests
- Add command line flag to enable API
- Conditionally register routes + handlers in the Eth2Runner

Let me know if I covered everything, and if it sounds accurate.

**Comment by dapplion** [comment]
Task breakdown looks great! Feel free to add it to the main issue body with
- [ ] This format
so it easier to get for external readers

**Comment by jframe** [comment]
@joaquim-verges Removing keys dynamically at runtime isn't currently supported. So we will have to take the approach of remove it from memory first and then removing the key file. This is something we will probably want to add to the ArtifactSignerProvider.

**Comment by yorickdowne** [comment]
Adding auth would be great.

**Comment by jframe** [comment]
Definitely would be. We have a ticket to implement that with https://github.com/ConsenSys/web3signer/issues/545
