### ISSUE TITLE
The Merge

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#486]
Everything needed to ensure that Web3Signer will support Ethereum after the merge.

**Tasks**

- [x] Only require block_body_root instead of full block bodyweb3signer #437
- [x] Setup Web3Signer on a merge testnetweb3signer #487
- [x] Investigate changes needed for the merge #459

**Comment by james-prysm** [comment]
Is block v3 one item? 🤔 will you be adding a list of check items?
