### ISSUE TITLE
Disable validator before deleting key

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#509]
Validators need to be disabled at the database level prevent other instances from inserting slashing protection data during and after the key manager delete API has been called.

**Tasks**
- [x] Modify the database schema so the active/disabled status can be set
- [x] In the DbSlashingProtection maySignAttestation and maySignBlock add a check to ensure the validator is active before attempting any checks or signing.
- [x] Add new method to update the disabled status in the appropriate Dao most likely the ValidatorsDao
- [ ] In the DeleteKeystoresProcessor disable the validator before exporting the slashing protection data.

**Acceptance Criteria**
- It is not possible for the slashing protection data to be inserted by any instance of web3signer once the key has been deleted
- If key files are added again the validator marked active again and sign data and insert records into the slashing protection database
