### ISSUE TITLE
Test gnosis chain

### ISSUE THREAD

**Issue by jframe** [ConsenSys/web3signer#544]
Test Web3Signer with gnosis chain. Teku has added a network configuration for gnosis so hopefully the only changes we need to do are update the version of Teku libraries used and test that Web3Signer is able to sign on the gnosis beacon chain.

Details on the gnosis beacon chain https://www.xdaichain.com/for-validators/consensus/sbc
Teku support for the gnosis beacon chain https://github.com/ConsenSys/teku/commit/4097026e4cfff4442aa274882a56c160454f2503

**Tasks**
- [ ] Determine what the timelines are for the gnosis beacon chain testnet and merge
- [ ] Investigate what we need to do setup a validator (Looks like Centaur have done this so talk to them?)
- [ ] Register validator on gnosis test network
- [ ] Configure and run Web3Signer and Teku configured for Gnosis. Need to run long enough to sign all data types

**Comment by wcgcyx** [comment]
Closed as gnosis beacon chain does not have a public testnet.
