### ISSUE TITLE
EIP-4844 Support

### ISSUE THREAD

**Issue by siladu** [Consensys/web3signer#857]
Notes 

We should only need one SignType for this e.g: BLOB_SIDECAR since the signature should end up being the same (may need to confirm this with CL client teams).

We believe the Merkleisation of BlobSidecar should be equivalent to BlindedBlobSidecar

We might not even need to pass all of the fields from BlindedBlobSidecar to web3signer, can we get away with just blob_root, slot and blob_index? Need to consider future slashing protection around blobs.

Tasks 

- [x] Spec out web3signer request for BLOB_SIDECAR - #867
- [x] Agree spec with CL teams
- [x] Investigate: EIP-7044 -  Perpetually Valid Signed Voluntary Exits https://github.com/Consensys/web3signer/issues/726#issuecomment-1653408452
- [x] #869: Implement signBlobSidecar and signBlindedBlobSidecar: https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java#L131-L144
  * SignedBlobSidecar: https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/validator.md#constructing-the-signedblobsidecars
  * SignedBlindedBlobSidecar: https://github.com/ethereum/builder-specs/blob/main/specs/deneb/builder.md#signedblindedblobsidecar
- [x] #869: Add to ExternalSignerIntegrationTest and/or new test ExternalSignerDenebBlockSigningIntegrationTest?
- [x] Web3signer: Handle BLOB_SIDECAR signing requests
- [x] Web3signer: Automated Tests
