### ISSUE TITLE
Tracker for Teku-Web3signer Integration

### ISSUE THREAD

**Issue by siladu** [Consensys/web3signer#869]
- Part of https://github.com/Consensys/web3signer/issues/857 epic
- Depends on JSON request shape https://github.com/Consensys/web3signer/issues/867

Tasks 

- [x] Create schema classes for json serialize/deserialize
- [x] Implement signBlobSidecar and signBlindedBlobSidecar: https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java#L131-L144
  * SignedBlobSidecar: https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/validator.md#constructing-the-signedblobsidecars
  * SignedBlindedBlobSidecar: https://github.com/ethereum/builder-specs/blob/main/specs/deneb/builder.md#signedblindedblobsidecar
- [x] Add to ExternalSignerIntegrationTest and/or new test ExternalSignerDenebBlockSigningIntegrationTest?

**Comment by usmansaleem** [comment]
Implemented via https://github.com/Consensys/teku/pull/7428
